### ISSUE TITLE
cURL timeout

### ISSUE THREAD

**Issue by tjerkhamer** [mailjet/mailjet-apiv3-php#157] opened 2018-11-20 18:14 UTC
A lot of times when we try to send an email through the wrapper, we experience a cURL timeout (2500 ms)

Today (and many times before) we send a request to the api with an almost empty html and text part and received an fatal error because of the timeout. The request came in on our server at 09:52:52, was the request to Mailjet started at 09:52:54 and received the timeout at 09:52:57.

A conversation with support @ mailjet didn't solve anything besides a work around to keep sending until the request is accepted by Mailjet, which isn't a very sustainable solution.

Can anybody please help us solve this problem, so we can start using Mailjet as our mailserver.

**Comment by kmanchikov** [comment] 2018-11-21 12:53
Hi Tjerk, 

The "cURL timeout (2500 ms)" should implement that this should be a hard limit for how long time a request is allowed to take, and yours seems to be set to 2.5sec. So in this case the request took a bit longer to reach Mailjet thus this request timed out. You could use 0 to wait indefinitely or set the limit to be equals to 20 seconds, as far as I know this is the maximum limit that Mailjet would take to handle the request.

**Comment by launtony** [comment] 2018-12-18 21:59
Hi guys, I have this problem since some days :/ I have increase the delay to 15sec but same problem :/ I suspect internet problem on my hosting provider OVH :/ But I don't know :( Any idea?

**Comment by todorDim** [comment] 2019-02-20 13:03
Hello @launtony,

Does the issue still persist ?

Regards,
T.

**Comment by launtony** [comment] 2019-02-20 14:16
Hi :) 

No problem since few weeks :) 

Do you have made some changes? 

Thanks,

**Comment by iMagicKey** [comment] 2019-03-01 13:52
Hello!
We still have this problem.
A couple of days ago we increased the timeout from 5 to 15 seconds, but this did not help.
cURL error 28: Operation timed out after 15001 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Does anyone know how to solve this problem?

**Comment by abambova** [comment] 2019-03-06 15:11
Hi @iMagicKey ,
We will test on our side the issue and come back to you with more details. Thanks!

**Comment by launtony** [comment] 2019-03-06 15:12
Hi,

I had this error yesterday (3 times) :/ 

Thanks,

**Comment by abambova** [comment] 2019-03-08 09:53
Hi @launtony and @iMagicKey ,
Could you please increase the timeout to 20s? Please let us know if it solves the issue you are facing. Thanks!

**Comment by iMagicKey** [comment] 2019-03-18 11:16
Hi @abambova,
we have errors again.

cURL error 28: Operation timed out after 20001 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Errors was happend in (GMT+1):
14.03.2019 14:00:09
15.03.2019 11:30:25
15.03.2019 11:31:20
15.03.2019 11:31:22
15.03.2019 11:31:46
16.03.2019 08:00:25
16.03.2019 08:00:45
16.03.2019 08:01:11
16.03.2019 08:01:15
18.03.2019 06:35:09

**Comment by nadar** [comment] 2019-03-21 13:03
We do have the timeout issues as well from time to time.

**Comment by abambova** [comment] 2019-03-26 09:06
Could you please contact our support team for that https://app.mailjet.com/support/ticket ? they will help you with solving this issue. Thanks!

**Comment by jkgroupe** [comment] 2019-06-26 08:12
> Hi guys, I have this problem since some days :/ I have increase the delay to 15sec but same problem :/ I suspect internet problem on my hosting provider OVH :/ But I don't know :( Any idea?

I think this problem comes from OVH because I have the same one

**Comment by launtony** [comment] 2019-06-26 17:02
@jkgroupe You think ? I haven't this error since few days now :) I have this error some times :/ I have developp a system on my app to retry just once if I have this error :/

**Comment by cbou** [comment] 2019-08-26 11:30
We have the same problem too.

In our case the issue is related to `CONNECT_TIMEOUT`. I increase it to 5 but it didn't help. Sometimes it works but sometimes it does not.

At the moment the code is under development so it's not a real issue but this could prevent us to deploy Mailjet :(

I hope it will be fixed soon.

**Comment by Golden21000** [comment] 2019-09-04 13:02
We have this problem too, again and again... Any solution ?

Mailjet support wants i install : 
- https://mitmproxy.org/ (able to catch the traffic)
- https://github.com/droe/sslsplit (inspect the bad requests inside)
to find a solution.

**Comment by jkgroupe** [comment] 2019-09-05 11:45
> @jkgroupe You think ? I haven't this error since few days now :) I have this error some times :/ I have developp a system on my app to retry just once if I have this error :/

In my case I have made a loop to retry to send the mail if I have a timeout and it works perfectly :)

**Comment by cbou** [comment] 2019-09-19 08:22
I was able to reproduce it twice the previous days so I guess it' still there.

My scenario was (all the steps in a loop 50 times): 
- Checking is a list was existing
- Creating it if not
- Add the a contact (50 different emails) to the list
- Get the contact information
- Send an email

Sometimes it pass and I receive 50 emails (most of the time) but sometimes I get the timeout error.

It would be interesting to know if other SDK has the problem.

**Comment by Lucassifoni** [comment] 2019-12-01 09:34
Hello,
We're experiencing the same random timeouts with multiple languages (PHP, Elixir) on multiple hosting providers (OVH, DigitalOcean). Increasing the timeout and / or re-queuing sends was the only solution for us.

**Comment by peter279k** [comment] 2020-04-08 18:05
I think this is a temporary error.

I get this connection timeout error, and I retry doing e-mail sending after few seconds.

Then it's successful.

**Comment by BigBenJr** [comment] 2020-08-28 09:28
I am implementing MailJet on my app, I experienced this cURL timeout several times since i am doing different local tests.
The last one doing this:

`$filters = ['ContactEmail' => 'xxx', 'ContactsList' => xxx, 'unsub' => false];
$response = $mj->get(\Mailjet\Resources::$Listrecipient, ['filters' => $filters]);
$response->success() && var_dump($response->getData());`

I got this:

> Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 2000 milliseconds

I refresh the request and then it's working... no timeout issue. But 10 minutes later I do the same request and I get an other cURL timeout again. I am afraid it may happen everytime... everywhere... to anyone using my app... ?

**Comment by Lucassifoni** [comment] 2020-08-31 14:26
Hello @BigBenJr ,
Expect timeouts on a regular basis in production. We implemented incremental retries in our app in a separate process to avoid complications. 

We try to send mail up to 6 times, retrying after 5, 15, 30, 60, 120, 240 seconds. After the sixth attempt, we log an exception and we get an e-mail (with another provider) alerting us. This already happened several times.

You can't prevent all failures but it's already something.

**Comment by uavn** [comment] 2020-11-13 13:00
Closing. Workaround mentioned in the comments, actually it is standard solution for such third-party integrations, and it is not about SDK, it is about mailjet API service.

**Closed by uavn** 2020-11-13 13:00 UTC
Labels: question

**Comment by liamcharmer** [comment] 2021-02-05 16:40
> Closing. Workaround mentioned in the comments, actually it is standard solution for such third-party integrations, and it is not about SDK, it is about mailjet API service.

So the "mentioned workaround" is to do what? 

From
```
  $response = $mj->post(Resources::$Email, ['body' => $body]);
```

to 
```
  $response = $mj->post(Resources::$Email, ['body' => $body,  'timeout' => 10000,  'connect_timeout' => 10000]);
```

We assume? And then retries?

**Comment by AnnoyingTechnology** [comment] 2023-01-31 15:04
@uavn May you answer the above post ?

**Comment by uavn** [comment] 2023-01-31 15:18
Sorry for not being clear about workaround:

Connection timeout means that API host is unreachable, service can be down or just overloaded, your network can be unstable, etc., it doesn't really matter.

The best solution (workaround) is to implement some retry logic, so you can add your mail job to the background queue (can be mysql + cron or amqp, or which way you preferer), and then try to execute it with some delays, if first attempt failed, call it in a few minutes, and maybe in a few minutes again if it failed, most probably it'll work fine from another try.

Sending email jobs to the background processes is a good practice anyway.

**Comment by AnnoyingTechnology** [comment] 2023-01-31 15:22
We do queue emails, but we are trying to weed out Mailjet API Errors that pollute logs files and alerting systems. 
Increasing the timeout to match the API's seems reasonable.

**Comment by uavn** [comment] 2023-01-31 15:54
@AnnoyingTechnology You can wrap it in `try` `catch` if not yet, and yes, increasing timeout can help sometime
