### ISSUE TITLE
Some recipient not receive Emails

### ISSUE THREAD

**Issue by MohmmadAnasShekhMousa** [mailjet/mailjet-apiv3-php#231] opened 2021-08-18 08:38 UTC
I use MailJet api v3 with Yii2 framework after integrate my code with mailjet api options and send messages to users, some users didn't receive emails from my system, I think I have something in Security in recipients accounts.

note I'm try send to google accounts as follow:

- XXX@gmail.com [received]
- YYY@gmail.com [not received]

how to I go back trace with this problem? or anywhere I can find report's deliver-ability?

**Comment by Pavlico** [comment] 2021-08-20 07:15
Well you can always get some additional info on your dashboard at https://app.mailjet.com/stats , there, failed messages should be described with types:

Soft Bounce: This is a temporary issue such as the recipient’s inbox is full or a connection timeout. Mailjet will automatically attempt to resend the email. If the email is not delivered in 24 hours, it is marked as a bounce.

Hard Bounce: This is a permanent delivery error caused by an invalid email address (e.g. a mistyped email, a non-existent destination server). Hard bounces negatively impact your sender reputations and are automatically blocked by Mailjet for 90 days.

about statuses you can get more info here: https://documentation.mailjet.com/hc/en-us/articles/360048398994-Email-statuses-all-metrics-explained-#h_6fe6fdc1-dde6-4034-a1bf-493a15212183

**Comment by Pavlico** [comment] 2021-09-15 12:11
No upadates from creator, seems like nothing more to add here, closing

**Closed by Pavlico** 2021-09-15 12:11 UTC
