### ISSUE TITLE
500 Invalid floating point operation

### ISSUE THREAD

**Issue by MarkVaughn** [mailjet/mailjet-apiv3-php#64] opened 2016-07-31 18:21 UTC
I'm trying to send out an email with your templating system, however the 500 response I am getting is to cryptic to understand. 500 **Invalid floating point operation**
```
    $smtp = $this->getConfig();
    $client = new Client($smtp->username, $smtp->password);
    $body = [
            'FromEmail' => 'info@example.com',
            'FromName' => "Test",
            'Mj-TemplateID' => $templateId,
            'MJ-TemplateLanguage' => true,
            'Subject' => $subject,
            'Vars' => $vars,
            'Recipients' => [
                [
                    'Email' => $to
                ]
            ]
        ];
     $response = $client->post(Resources::$Email, $body);
```

And this is the response
```
object(Mailjet\Response)[200]
  private 'status' => int 500
  private 'success' => boolean false
  private 'body' => null
  public 'request' => 
    object(Mailjet\Request)[171]
      private 'method' => string 'POST' (length=4)
      private 'url' => string 'https://api.mailjet.com/v3/send' (length=31)
      private 'filters' => 
        array (size=0)
          empty
      private 'body' => string '{}' (length=2)
      private 'auth' => 
        array (size=2)
          0 => string '285[REDACTED]' (length=32)
          1 => string '791[REDACTED]' (length=32)
      private 'type' => string 'application/json' (length=16)
      private 'messageFactory' (GuzzleHttp\Client) => 
        object(GuzzleHttp\Message\MessageFactory)[174]
          private 'errorPlugin' => 
            object(GuzzleHttp\Subscriber\HttpError)[175]
              ...
          private 'redirectPlugin' => 
            object(GuzzleHttp\Subscriber\Redirect)[176]
              ...
          private 'customOptions' => 
            array (size=0)
              ...
      private 'baseUrl' (GuzzleHttp\Client) => 
        object(GuzzleHttp\Url)[173]
          private 'scheme' => string '' (length=0)
          private 'host' => string '' (length=0)
          private 'port' => null
          private 'username' => null
          private 'password' => null
          private 'path' => string '' (length=0)
          private 'fragment' => null
          private 'query' => null
      private 'defaults' (GuzzleHttp\Client) => 
        array (size=5)
          'allow_redirects' => boolean true
          'exceptions' => boolean true
          'decode_content' => boolean true
          'verify' => boolean true
          'headers' => 
            array (size=1)
              ...
      private 'fsm' (GuzzleHttp\Client) => 
        object(GuzzleHttp\RequestFsm)[181]
          private 'handler' => 
            object(Closure)[180]
              ...
          private 'mf' => 
            object(GuzzleHttp\Message\MessageFactory)[174]
              ...
          private 'maxTransitions' => int 200
      private 'emitter' (GuzzleHttp\Client) => 
        object(GuzzleHttp\Event\Emitter)[182]
          private 'listeners' => 
            array (size=0)
              ...
          private 'sorted' => 
            array (size=0)
              ...
  public 'rawResponse' => 
    object(GuzzleHttp\Message\Response)[222]
      private 'reasonPhrase' => string 'Invalid floating point operation' (length=32)
      private 'statusCode' => int 500
      private 'effectiveUrl' => string 'https://api.mailjet.com/v3/send' (length=31)
      private 'headers' (GuzzleHttp\Message\AbstractMessage) => 
        array (size=6)
          'server' => 
            array (size=1)
              ...
          'date' => 
            array (size=1)
              ...
          'content-type' => 
            array (size=1)
              ...
          'content-length' => 
            array (size=1)
              ...
          'connection' => 
            array (size=1)
              ...
          'vary' => 
            array (size=1)
              ...
      private 'headerNames' (GuzzleHttp\Message\AbstractMessage) => 
        array (size=6)
          'server' => string 'Server' (length=6)
          'date' => string 'Date' (length=4)
          'content-type' => string 'Content-Type' (length=12)
          'content-length' => string 'Content-Length' (length=14)
          'connection' => string 'Connection' (length=10)
          'vary' => string 'Vary' (length=4)
      private 'body' (GuzzleHttp\Message\AbstractMessage) => 
        object(GuzzleHttp\Stream\Stream)[221]
          private 'stream' => resource(286, stream)
          private 'size' => null
          private 'seekable' => boolean true
          private 'readable' => boolean true
          private 'writable' => boolean true
          private 'uri' => string 'php://temp' (length=10)
          private 'customMetadata' => 
            array (size=0)
              ...
      private 'protocolVersion' (GuzzleHttp\Message\AbstractMessage) => string '1.1' (length=3)
```

**Comment by MarkVaughn** [comment] 2016-07-31 18:46
more information:
I know the credentials are right using this example
```
$smtp = $this->getConfig();
$client = new Client($smtp->username, $smtp->password);
$body = [
    'Email' => "info@example.com"
];
$response = $client->post(Resources::$Sender, ['body' => $body]);
```
I get a 400 saying I already added my email, so I can assume the credentials are correct.

Using the second example
```
$body = [
    'FromEmail' => "info@example.com",
    'FromName' => "Test",
    'Subject' => "Your email flight plan!",
    'Text-part' => "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
    'Html-part' => "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
    'Recipients' => [
        [
            'Email' => "passenger@mailjet.com"
        ]
    ]
];
$response = $client->post(Resources::$Email, ['body' => $body]);
```
I get the same 500 error. Usually 500 errors are server errors, so maybe this is on the mailjet end?

**Comment by arnaudbreton** [comment] 2016-08-09 14:39
Hi @MarkVaughn,

Apologies for the delay in our answer. Since we're already discussing your issue with our regular support and since it doesn't seem to be related to our PHP wrapper but more on the API side, I propose we continue the discussion there. I'm closing the issue for now. We'll reopen in case there is a fix to apply in the wrapper itself.

Thanks for sharing your different payloads. I haven't managed yet to reproduce your issue so we'll continue to dig into this.

Thanks for your patience,
Best.

**Closed by arnaudbreton** 2016-08-09 14:39 UTC

**Comment by David-Vander-Elst** [comment] 2016-12-06 10:00
Hello

I have the same issue when using the client.

This is a 500 internal server error so it occur on the end side, but I don't have the problem when directly test a curl command with the same parameters, so I guess something is wrong with the wrapper that create the HTTP query.

Curl method:

```
curl -v -s \
  -X POST \
  --user "xxx:xxx" \
  https://api.mailjet.com/v3/send \
  -H 'Content-Type: application/json' \
  -d '{
    "FromEmail":"david.vanderelst@xxx.xxx",
    "FromName":"Test",
    "Subject":"bla",
    "Text-part":"bla",
    "Html-part":"bla",
    "Recipients":[
        {
            "Email": "david.vanderelst@xxx.xxx"
        }
    ]
  }'
``` 

Response : 

```
*   Trying 5.135.120.255...
* Connected to api.mailjet.com (5.135.120.255) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.mailjet.com
* Server certificate: GeoTrust SSL CA - G3
* Server certificate: GeoTrust Global CA
* Server auth using Basic with user 'xxx'
> POST /v3/send HTTP/1.1
> Host: api.mailjet.com
> Authorization: Basic XXXXX=
> User-Agent: curl/7.47.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 239
> 
* upload completely sent off: 239 out of 239 bytes
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 06 Dec 2016 09:57:27 GMT
< Content-Type: application/json
< Content-Length: 95
< Connection: keep-alive
< 
{ "Sent" : [{ "Email" : "david.vanderelst@xxx.xxx", "MessageID" : 205xxxx000 }] }
* Connection #0 to host api.mailjet.com left intact

```

Trying with the PHP client:

```
<?php

namespace MyNamespace\MailJet;

require __DIR__ . '/vendor/autoload.php';

use Mailjet\Client;
use Mailjet\Resources;

$publicKey = 'xxx';
$privateKey = 'xxx';

$mj = new Client($publicKey, $privateKey);

$response = $mj->post(Resources::$Email, [
    'FromEmail' => "david.vanderelst@xxx.xxx",
    'FromName' => "Test",
    'Subject' => "bla",
    'Text-part' => "bla",
    'Html-part' => "bla",
    'Recipients' => [
        ['Email' => "david.vanderelst@xxx.xxx"]
    ]
]);

if ($response->success()) {
    var_dump($response->getData());
} else {
    var_dump($response->getReasonPhrase());
}
```

Response:

> string(32) "Invalid floating point operation"

**Comment by Zhivko-Mailjet** [comment] 2016-12-06 10:27
Hi @MarkVaughn ,

This error is usually generated when you are not passing the body of the request properly. With the PHP wrapper, you need to substitute the 'body' property with the real payload.
For example:
`$response = $mj->post(Resources::$Email, ['body' => $body]);`
where $body = [
    'FromEmail' => "david.vanderelst@xxx.xxx",
    'FromName' => "Test",
    'Subject' => "bla",
    'Text-part' => "bla",
    'Html-part' => "bla",
    'Recipients' => [
        ['Email' => "david.vanderelst@xxx.xxx"]
    ]
];

See here:
https://github.com/mailjet/mailjet-apiv3-php#send-transactional-emails

**Comment by David-Vander-Elst** [comment] 2016-12-06 10:45
Indeed, my bad.

Thanks
