### ISSUE TITLE
400 At least 1 "to" value required in example requests

### ISSUE THREAD

**Issue by justintelmo** [mailjet/mailjet-apiv3-php#173] opened 2019-06-11 01:45 UTC
Hi,

I am currently having an issue with the V3 API on any send request. It is returning with an error code 400 with at least 1 "to" value required. I am using the same request body as in the documentation example, but I am still getting this error. I have checked my credentials and they are correct. 

This is the body of the request, with details edited out:
```
{
    "Messages": [
        {
            "FromEmail": "xxxxx@xxxx.xxxx",
            "FromName": "Your Mailjet Pilot",
            "Sender": true,
            "Recipients": [
                {
                    "Email": "justin.telmo@xxxx.xxx",
                    "Name": "Justin Telmo"
                }
            ],
            "Cc": "Passenger 2 <passenger2@mailjet.com>",
            "Bcc": "Passenger 3 <passenger3@mailjet.com>",
            "Subject": "Your email flight plan!",
            "Text-part": "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
            "Html-part": "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
            "Mj-TemplateID": 123456,
            "Mj-TemplateLanguage": false,
            "Mj-TemplateErrorReporting": "reports@example.com",
            "Mj-TemplateErrorDeliver": 0,
            "Attachments": [
                {
                    "Filename": "test.txt",
                    "Content-type": "text/plain",
                    "Content": "VGhpcyBpcyB5b3VyIGF0dGFjaGVkIGZpbGUhISEK"
                }
            ],
            "Inline_attachments": [
                {
                    "Filename": "logo.gif",
                    "Content-type": "image/gif",
                    "Content": "R0lGODlhEAAQAOYAAP////748v39/Pvq1vr6+lJSVeqlK/zqyv7+/unKjJ+emv78+fb29pucnfrlwvTCi9ra2vTCa6urrWdoaurr6/Pz8uHh4vn49PO7QqGfmumaN+2uS1ZWWfr27uyuLnBxd/z8+0pLTvHAWvjar/zr2Z6cl+jal+2kKmhqcEJETvHQbPb07lBRVPv6+cjJycXFxn1+f//+/f337nF0efO/Mf306NfW0fjHSJOTk/TKlfTp0Prlx/XNj83HuPfEL+/v8PbJgueXJOzp4MG8qUNES9fQqN3d3vTJa/vq1f317P769f/8+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH/C1hNUCBEYXRhWE1QPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS4wLWMwNjAgNjEuMTM0Nzc3LCAyMDEwLzAyLzEyLTE3OjMyOjAwICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdFJlZj0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlUmVmIyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MjY5ODYxMzYzMkJCMTFFMDkzQkFFMkFENzVGN0JGRkYiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MjY5ODYxMzczMkJCMTFFMDkzQkFFMkFENzVGN0JGRkYiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDoyNjk4NjEzNDMyQkIxMUUwOTNCQUUyQUQ3NUY3QkZGRiIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDoyNjk4NjEzNTMyQkIxMUUwOTNCQUUyQUQ3NUY3QkZGRiIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PgH//v38+/r5+Pf29fTz8vHw7+7t7Ovq6ejn5uXk4+Lh4N/e3dzb2tnY19bV1NPS0dDPzs3My8rJyMfGxcTDwsHAv769vLu6ubi3trW0s7KxsK+urayrqqmop6alpKOioaCfnp2cm5qZmJeWlZSTkpGQj46NjIuKiYiHhoWEg4KBgH9+fXx7enl4d3Z1dHNycXBvbm1sa2ppaGdmZWRjYmFgX15dXFtaWVhXVlVUU1JRUE9OTUxLSklIR0ZFRENCQUA/Pj08Ozo5ODc2NTQzMjEwLy4tLCsqKSgnJiUkIyIhIB8eHRwbGhkYFxYVFBMSERAPDg0MCwoJCAcGBQQDAgEAACH5BAEAAAAALAAAAAAQABAAAAdUgACCg4SFhoeIiYRGLhaKhA0TMDgSLxAUiEIZHAUsIUQpKAo9Og6FNh8zJUNFJioYQIgJRzc+NBEkiAcnBh4iO4o8QRsjj0gaOY+CDwPKzs/Q0YSBADs="
                }
            ],
            "Mj-prio": 2,
            "Mj-campaign": "SendAPI_campaign",
            "Mj-deduplicatecampaign": 1,
            "Mj-trackopen": 0,
            "Mj-CustomID": "CustomValue",
            "Mj-EventPayload": "Eticket,1234,row,15,seat,B",
            "Mj-MonitoringCategory": "Category1",
            "Headers": "object",
            "Vars": "object"
        }
    ]
}
```

**Comment by adamyanliev** [comment] 2019-06-11 07:30
hey @justintelmo ,

The issue is that you're using both `Recipients` and `Cc` / `Bcc` in your payload. `Cc` and `Bcc` cannot be used together with `Recipients` - you need to use `To` instead. See the [API reference](https://dev.mailjet.com/reference/email/send-emails/#v3_post_send) for more info.

Alternatively, you can simply add all of your recipients in the `Recipients` array. this will hide the recipients from each other, unlike when using `To` and `Cc`.

Let us know if this solved your issue :) 

Regards,
Atanas

**Comment by justintelmo** [comment] 2019-06-11 18:41
@adamyanliev 

I updated the payload to look like this and I still get the same exact error.

```
{
    "Messages": [
        {
            "FromEmail": "xxxxx@xxxxx.xxxx",
            "FromName": "Your Mailjet Pilot",
            "Sender": true,
            "Recipients": [
                  {
                      "Email": "justin.telmo@xxxxxxx.xxxx",
                      "Name": "Justin Telmo"
                  }
             ],
            "Subject": "Your email flight plan!",
            "Text-part": "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
            "Html-part": "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
            "Attachments": [
                {
                    "Filename": "test.txt",
                    "Content-type": "text/plain",
                    "Content": "VGhpcyBpcyB5b3VyIGF0dGFjaGVkIGZpbGUhISEK"
                }
            ],
            "Inline_attachments": [
                {
                    "Filename": "logo.gif",
                    "Content-type": "image/gif",
                    "Content": "R0lGODlhEAAQAOYAAP////748v39/Pvq1vr6+lJSVeqlK/zqyv7+/unKjJ+emv78+fb29pucnfrlwvTCi9ra2vTCa6urrWdoaurr6/Pz8uHh4vn49PO7QqGfmumaN+2uS1ZWWfr27uyuLnBxd/z8+0pLTvHAWvjar/zr2Z6cl+jal+2kKmhqcEJETvHQbPb07lBRVPv6+cjJycXFxn1+f//+/f337nF0efO/Mf306NfW0fjHSJOTk/TKlfTp0Prlx/XNj83HuPfEL+/v8PbJgueXJOzp4MG8qUNES9fQqN3d3vTJa/vq1f317P769f/8+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH/C1hNUCBEYXRhWE1QPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS4wLWMwNjAgNjEuMTM0Nzc3LCAyMDEwLzAyLzEyLTE3OjMyOjAwICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdFJlZj0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlUmVmIyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ1M1IFdpbmRvd3MiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MjY5ODYxMzYzMkJCMTFFMDkzQkFFMkFENzVGN0JGRkYiIHhtcE1NOkRvY3VtZW50SUQ9InhtcC5kaWQ6MjY5ODYxMzczMkJCMTFFMDkzQkFFMkFENzVGN0JGRkYiPiA8eG1wTU06RGVyaXZlZEZyb20gc3RSZWY6aW5zdGFuY2VJRD0ieG1wLmlpZDoyNjk4NjEzNDMyQkIxMUUwOTNCQUUyQUQ3NUY3QkZGRiIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDoyNjk4NjEzNTMyQkIxMUUwOTNCQUUyQUQ3NUY3QkZGRiIvPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/PgH//v38+/r5+Pf29fTz8vHw7+7t7Ovq6ejn5uXk4+Lh4N/e3dzb2tnY19bV1NPS0dDPzs3My8rJyMfGxcTDwsHAv769vLu6ubi3trW0s7KxsK+urayrqqmop6alpKOioaCfnp2cm5qZmJeWlZSTkpGQj46NjIuKiYiHhoWEg4KBgH9+fXx7enl4d3Z1dHNycXBvbm1sa2ppaGdmZWRjYmFgX15dXFtaWVhXVlVUU1JRUE9OTUxLSklIR0ZFRENCQUA/Pj08Ozo5ODc2NTQzMjEwLy4tLCsqKSgnJiUkIyIhIB8eHRwbGhkYFxYVFBMSERAPDg0MCwoJCAcGBQQDAgEAACH5BAEAAAAALAAAAAAQABAAAAdUgACCg4SFhoeIiYRGLhaKhA0TMDgSLxAUiEIZHAUsIUQpKAo9Og6FNh8zJUNFJioYQIgJRzc+NBEkiAcnBh4iO4o8QRsjj0gaOY+CDwPKzs/Q0YSBADs="
                }
            ],
            "Mj-prio": 2,
            "Mj-campaign": "SendAPI_campaign",
            "Mj-deduplicatecampaign": 1,
            "Mj-trackopen": 0,
            "Mj-CustomID": "CustomValue",
            "Mj-EventPayload": "Eticket,1234,row,15,seat,B",
            "Mj-MonitoringCategory": "Category1",
            "Headers": "object",
            "Vars": "object"
        }
    ]
}
```

**Comment by adamyanliev** [comment] 2019-06-12 14:48
hi @justintelmo ,

Looks like you're using the example in the Postman collection. With the above payload you should not be getting the error that `To` is required, but instead a `400 "Headers" is not JSON object type"`. Both the `Headers` and `Vars` properties are objects that need to be defined - see [this](https://dev.mailjet.com/guides/index.html#adding-email-headers-v3) for an example on how to use headers and [this](https://dev.mailjet.com/guides/index.html#using-vars-and-custom-vars-v3) for variables. 

Both are not defined in the payload example, as it's up to you to decide what kind of variables and headers you want to use for your messages. Once those are defined (or removed from the payload altogether) you should have no issues with sending the message. 

Let me know if this solves your issue.

Atanas

**Comment by uavn** [comment] 2020-11-13 13:03
Answered, closing.

**Closed by uavn** 2020-11-13 13:03 UTC
